"""add career preferences

Revision ID: 32a04abc6b25
Revises: 7514ffb998fb
Create Date: 2026-09-17 17:59:12.346935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32a04abc6b25'
down_revision: Union[str, Sequence[str], None] = '7514ffb998fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_preferences',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('target_roles', sa.Text(), nullable=True),
    sa.Column('preferred_locations', sa.Text(), nullable=True),
    sa.Column('remote_preference', sa.String(length=50), nullable=True),
    sa.Column('employment_types', sa.Text(), nullable=True),
    sa.Column('minimum_salary', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('willing_to_relocate', sa.Boolean(), nullable=True),
    sa.Column('preferred_experience_level', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['career_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_preferences_profile_id'), 'career_preferences', ['profile_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_preferences_profile_id'), table_name='career_preferences')
    op.drop_table('career_preferences')
    # ### end Alembic commands ###
