"""normalize job requirement skills

Revision ID: 4771c49de705
Revises: 7ee20b3691d0
Create Date: 2026-09-18 17:03:49.095449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4771c49de705'
down_revision: Union[str, Sequence[str], None] = '7ee20b3691d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_requirement_skills',
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['job_requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill_catalog.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_requirement_skills_requirement_id'), 'job_requirement_skills', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_job_requirement_skills_skill_id'), 'job_requirement_skills', ['skill_id'], unique=False)
    op.drop_index(op.f('ix_job_requirements_normalized_skill_id'), table_name='job_requirements')
    op.drop_constraint(op.f('job_requirements_normalized_skill_id_fkey'), 'job_requirements', type_='foreignkey')
    op.drop_column('job_requirements', 'normalized_skill_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_requirements', sa.Column('normalized_skill_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('job_requirements_normalized_skill_id_fkey'), 'job_requirements', 'skill_catalog', ['normalized_skill_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_job_requirements_normalized_skill_id'), 'job_requirements', ['normalized_skill_id'], unique=False)
    op.drop_index(op.f('ix_job_requirement_skills_skill_id'), table_name='job_requirement_skills')
    op.drop_index(op.f('ix_job_requirement_skills_requirement_id'), table_name='job_requirement_skills')
    op.drop_table('job_requirement_skills')
    # ### end Alembic commands ###
