"""add skill catalog and aliases

Revision ID: e40be46c0f04
Revises: d255dabdaa64
Create Date: 2026-09-17 18:07:05.759520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e40be46c0f04'
down_revision: Union[str, Sequence[str], None] = 'd255dabdaa64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_catalog',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_catalog_name'), 'skill_catalog', ['name'], unique=True)
    op.create_table('skill_aliases',
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=150), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skill_catalog.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_aliases_alias'), 'skill_aliases', ['alias'], unique=True)
    op.create_index(op.f('ix_skill_aliases_skill_id'), 'skill_aliases', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_aliases_skill_id'), table_name='skill_aliases')
    op.drop_index(op.f('ix_skill_aliases_alias'), table_name='skill_aliases')
    op.drop_table('skill_aliases')
    op.drop_index(op.f('ix_skill_catalog_name'), table_name='skill_catalog')
    op.drop_table('skill_catalog')
    # ### end Alembic commands ###
