"""add job ingestion metadata

Revision ID: fa6cb9fab1b8
Revises: 4771c49de705
Create Date: 2026-09-22 16:08:12.880137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa6cb9fab1b8'
down_revision: Union[str, Sequence[str], None] = '4771c49de705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('canonical_url', sa.String(length=1000), nullable=True))
    op.add_column('jobs', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('jobs', sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_jobs_canonical_url'), 'jobs', ['canonical_url'], unique=False)
    op.create_index(op.f('ix_jobs_content_hash'), 'jobs', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_content_hash'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_canonical_url'), table_name='jobs')
    op.drop_column('jobs', 'ingested_at')
    op.drop_column('jobs', 'content_hash')
    op.drop_column('jobs', 'canonical_url')
    # ### end Alembic commands ###
